name: Scale Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, asg-runner]

    strategy:
      matrix:
        job: [1,2,3,4,5,6,7,8]

    steps:
      - name: Print job
        run: |
          echo "Running job ${{ matrix.job }}"
          sleep 60
