name: Auto Scaling Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        job: [1, 2, 3, 4]

    steps:
      - name: Show runner
        run: hostname

      - name: Check Docker
        run: docker --version

      - name: Run container (simulate load)
        run: docker run -d python:3.9 sleep 180

      - name: Show running containers
        run: docker ps

      - name: Wait (keep job alive)
        run: sleep 90
