name: Load Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:

      # SMALL
      - name: Small Image
        run: docker run --rm nginx

      # MEDIUM
      - name: Medium Image
        run: docker run --rm node:18 node -e "console.log('test')"

      # LARGE
      - name: Large Image
        run: docker run -d mcr.microsoft.com/dotnet/sdk:7.0 sleep 120
