name: Docker Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Pull small image
        run: docker pull nginx

      - name: Pull medium image
        run: docker pull node:18

      - name: Pull large image
        run: docker pull mcr.microsoft.com/dotnet/sdk:7.0
